const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: "#000",
    textDisabled: "#bbb",
    placeholderText: "#ddd",
    background: "#EEE",
    containerBackgroundDefault: "#fff",
    menuItemDefault: "#fff",
    menuItemPressed: "#F5F5F5",
    modalBackground: "#eee",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
    tabBackgroundDefault: "#eee",
    tabBackgroundSelected: "#ddd",
    tabBackgroundPressed: "#ddd",
    buttonBackgroundDefault: "#FFFFFF",
    buttonBackgroundPressed: "#F5F5F5",
    borderColor: "#ddd",
  },
  dark: {
    text: "#fff",
    textDisabled: "#aaa",
    placeholderText: "#222222",
    background: "#101010",
    containerBackgroundDefault: "#666",
    menuItemDefault: "#101010",
    menuItemPressed: "#222222",
    modalBackground: "#888",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
    tabBackgroundDefault: "#666",
    tabBackgroundSelected: "#444",
    tabBackgroundPressed: "#444",
    buttonBackgroundDefault: "#101010",
    buttonBackgroundPressed: "#222222",
    borderColor: "#444",
  },
};
